# Generated by Django 3.0 on 2022-04-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title_tag',
            field=models.CharField(default='ELITE', max_length=255),
        ),
    ]
