# Generated by Django 3.0 on 2022-04-06 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220406_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
