# Generated by Django 3.0 on 2022-04-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220408_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='snippet',
            field=models.CharField(default='Click above to read more', max_length=255),
        ),
    ]
