# Generated by Django 4.0 on 2022-08-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
